[package]
name = "rust-csv-to-xlsx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
morse = "0.1.0"
rust_xlsxwriter = "0.54.0"